name: ci
on: [pull_request, workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        include:
          # Windows builds
          - os: windows-latest
            arch: aarch64
          - os: windows-latest
            arch: x86
          - os: windows-latest
            arch: x86_64
          # macOS builds
          - os: macos-latest
            arch: aarch64
          - os: macos-latest
            arch: x86_64
          # Linux builds
          - os: ubuntu-latest
            arch: aarch64
          - os: ubuntu-latest
            arch: armv7a
          - os: ubuntu-latest
            arch: powerpc64le
          - os: ubuntu-latest
            arch: riscv64
          - os: ubuntu-latest
            arch: s390x
          - os: ubuntu-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86_64
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - name: Install zig
        uses: mlugg/setup-zig@v2
      - run: zig build test --summary all
